/**
 * The determinism contract (§8.2): the primitives a generator uses to emit
 * byte-identical output, plus the checker that proves it did.
 *
 * The contract is narrow and absolute — no timestamps, no host names, no absolute
 * paths, no randomness — because the golden-file tests (§12 regime A) compare bytes
 * and a single timestamp turns every regeneration into a diff. `scanForNonDeterminism`
 * is what makes the contract testable instead of aspirational: a generator's own
 * tests run the emitted set through it, and a violation fails the build.
 *
 * The contract applies to *generated code*, never to model output (§8.2).
 */

import { createHash } from 'node:crypto';

import type { GeneratedFile } from './plan.js';

export const GENERATED_BANNER_MARKER = 'Code generated by AID Framework';

export interface BannerOptions {
  generator: string;
  version: string;
  /** Line-comment prefix for the target language. */
  comment?: string;
}

/**
 * The banner every generated file carries. It deliberately names the generator and
 * version but never a time: `aid doctor` compares the version, and a timestamp would
 * make every regeneration a spurious diff.
 */
export function generatedBanner(options: BannerOptions): string {
  const comment = options.comment ?? '//';
  return [
    `${comment} ${GENERATED_BANNER_MARKER} "${options.generator}" v${options.version}. DO NOT EDIT.`,
    `${comment} Owned by the generator: regenerate with \`aid gen\`. See aid.manifest.json.`,
  ].join('\n');
}

export function normalizeNewlines(text: string): string {
  return text.replace(/\r\n?/g, '\n');
}

/**
 * Exactly one trailing newline, and no trailing blank lines.
 *
 * The run is stripped with a loop rather than `/\n+$/`, which backtracks from every
 * start position when the run is not at the end of the string and is quadratic there.
 */
export function ensureTrailingNewline(text: string): string {
  let end = text.length;
  while (end > 0 && text[end - 1] === '\n') end--;
  return `${text.slice(0, end)}\n`;
}

/** Canonical text: LF endings, no trailing blank lines, exactly one trailing newline. */
export function normalizeText(text: string): string {
  return ensureTrailingNewline(normalizeNewlines(text));
}

export function sha256Hex(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

export function compareIds(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

/** Stable ordering by a string key. Ties keep their input order. */
export function stableSortBy<T>(items: readonly T[], key: (item: T) => string): T[] {
  return items
    .map((item, index) => ({ item, index }))
    .sort((left, right) => {
      const order = compareIds(key(left.item), key(right.item));
      return order === 0 ? left.index - right.index : order;
    })
    .map((entry) => entry.item);
}

/** Orders IR-named nodes by their stable `id`, so output never depends on input order. */
export function sortById<T extends { id: string }>(items: readonly T[]): T[] {
  return stableSortBy(items, (item) => item.id);
}

export function sortByPath<T extends { path: string }>(items: readonly T[]): T[] {
  return stableSortBy(items, (item) => item.path);
}

/**
 * A derived identifier for content that needs a stable suffix. Hashing keeps it
 * deterministic, which `Math.random()`/UUID would not.
 */
export function stableId(namespace: string, value: string): string {
  return `${namespace}-${sha256Hex(value).slice(0, 12)}`;
}

export interface DeterminismPattern {
  id: string;
  reason: string;
  pattern: RegExp;
}

/**
 * The forbidden shapes, as text patterns. This is a text-level lint, so it can only
 * catch what is visible in the emitted bytes; it is deliberately blunt because a
 * false positive is cheap (the generator drops the value) and a false negative is a
 * permanently churning golden file.
 */
export const DETERMINISM_PATTERNS: readonly DeterminismPattern[] = [
  {
    id: 'absolute-path-windows',
    reason: 'an absolute Windows path leaks the generating machine',
    pattern: /[A-Za-z]:[\\/]/,
  },
  {
    id: 'absolute-path-unix',
    reason: 'an absolute Unix path leaks the generating machine',
    pattern: /(?:^|[^A-Za-z0-9_.])\/(?:home|Users|tmp|var)\//,
  },
  {
    id: 'host-directory',
    reason: 'a host-specific directory leaks the generating machine',
    pattern: /AppData[\\/]|[/\\]\.venv[/\\]/,
  },
  {
    id: 'timestamp',
    reason: 'a timestamp makes every regeneration a diff',
    pattern: /\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}/,
  },
  {
    id: 'generated-at-phrase',
    reason: 'a generation date makes every regeneration a diff',
    pattern: /\bgenerated\s+(?:on|at)\b/i,
  },
  {
    id: 'hostname',
    reason: 'a host name leaks the generating machine',
    pattern: /\bhostname\s*[:=]/i,
  },
  {
    id: 'runtime-randomness',
    reason: 'generation-time randomness cannot be reproduced',
    pattern: /\b(?:Math\.random|crypto\.randomUUID|uuid4\()/,
  },
];

export interface DeterminismViolation {
  path: string;
  pattern: string;
  reason: string;
  line: number;
  text: string;
}

/** Reports every non-deterministic shape in one emitted file, in line order. */
export function scanForNonDeterminism(path: string, content: string): DeterminismViolation[] {
  const violations: DeterminismViolation[] = [];
  const lines = content.split('\n');

  for (const [index, line] of lines.entries()) {
    for (const candidate of DETERMINISM_PATTERNS) {
      if (!candidate.pattern.test(line)) continue;
      violations.push({
        path,
        pattern: candidate.id,
        reason: candidate.reason,
        line: index + 1,
        text: line.trim(),
      });
    }
  }
  return violations;
}

/** Reports every non-deterministic shape across a whole emitted set, ordered by path. */
export function checkDeterminism(files: readonly GeneratedFile[]): DeterminismViolation[] {
  return sortByPath(files).flatMap((file) => scanForNonDeterminism(file.path, file.content));
}
