/**
 * Ownership and path rules (§8.3, §8.4, §10).
 *
 * The three-tier split is the whole reason regeneration is safe: `generated/` is
 * generator-owned and never hand-edited, `business/` is developer-owned and written
 * once, and the ownership of a path is decided by *where it lives*, not by what a
 * generator happens to say about it. Every path in a plan is normalized through this
 * module, so a generator cannot escape its own root or claim a business path as
 * generated (or the reverse).
 */

export type FileOwner = 'generated' | 'business';

export const DEFAULT_GENERATED_DIR = 'generated';
export const DEFAULT_BUSINESS_DIR = 'business';

/** The ownership manifest. Generator bookkeeping, so it is never a planned artifact. */
export const DEFAULT_MANIFEST_FILENAME = 'aid.manifest.json';

/** The rejected-content sidecar: the newly generated bytes that were *not* written. */
export const REJECTION_SUFFIX = '.aid-rej';

/**
 * Normalizes a plan path to a repo-relative POSIX path: backslashes become
 * separators, `.` segments are dropped, and a leading `./` or `/` is removed.
 * Returns `undefined` for a path that cannot be expressed relative to the root.
 * `..` segments are preserved here so `escapesRoot` can report them as an error
 * rather than this function silently absorbing them.
 */
export function normalizeRelativePath(path: string): string | undefined {
  const trimmed = path.trim().replace(/\\/g, '/');
  if (trimmed === '') return undefined;
  if (/^[A-Za-z]:\//.test(trimmed)) return undefined;

  const segments = trimmed.split('/').filter((segment) => segment !== '' && segment !== '.');
  if (segments.length === 0) return undefined;
  if (segments.includes('..')) return undefined;

  return segments.join('/');
}

export function isRelativePath(path: string): boolean {
  return normalizeRelativePath(path) !== undefined;
}

/** True when the path climbs above its root. Reported instead of normalized away. */
export function escapesRoot(path: string): boolean {
  const segments = path.trim().replace(/\\/g, '/').split('/');
  return segments.includes('..');
}

export function isAbsolutePath(path: string): boolean {
  const trimmed = path.trim();
  return /^[A-Za-z]:[\\/]/.test(trimmed) || trimmed.startsWith('/') || trimmed.startsWith('\\\\');
}

/** Drops a trailing run of `/`. A loop, not `/\/+$/`, which is quadratic when the
 *  run is not at the end of the string. Root dirs are short, but not attacker-fixed. */
function stripTrailingSlashes(value: string): string {
  let end = value.length;
  while (end > 0 && value[end - 1] === '/') end--;
  return value.slice(0, end);
}

/**
 * The owner of a path, from its first segment. Anything outside both roots has no
 * owner, which is how a plan that reaches outside the two managed tiers is caught.
 */
export function ownerForPath(
  path: string,
  options: { generatedDir?: string; businessDir?: string } = {},
): FileOwner | undefined {
  const normalized = normalizeRelativePath(path);
  if (normalized === undefined) return undefined;

  const generatedDir = stripTrailingSlashes(options.generatedDir ?? DEFAULT_GENERATED_DIR);
  const businessDir = stripTrailingSlashes(options.businessDir ?? DEFAULT_BUSINESS_DIR);

  if (normalized === generatedDir || normalized.startsWith(`${generatedDir}/`)) return 'generated';
  if (normalized === businessDir || normalized.startsWith(`${businessDir}/`)) return 'business';
  return undefined;
}

export function isGeneratedPath(
  path: string,
  options: { generatedDir?: string; businessDir?: string } = {},
): boolean {
  return ownerForPath(path, options) === 'generated';
}

export function isBusinessPath(
  path: string,
  options: { generatedDir?: string; businessDir?: string } = {},
): boolean {
  return ownerForPath(path, options) === 'business';
}

/** Where rejected generated content lands: alongside the file it could not replace. */
export function rejectionPath(path: string): string {
  return `${path}${REJECTION_SUFFIX}`;
}

/** True when the path is the manifest itself or a rejection sidecar, never planned. */
export function isReservedPath(path: string, manifestFilename: string): boolean {
  const normalized = normalizeRelativePath(path);
  if (normalized === undefined) return false;
  return normalized === manifestFilename || normalized.endsWith(REJECTION_SUFFIX);
}
